# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0002_auto_20170804_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlatexcode',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added to the database'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songlatexcode',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated to the database'),
        ),
    ]
