# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0003_auto_20170804_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='paragraph',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='songwriter.Paragraph'),
            preserve_default=False,
        ),
    ]
