# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0004_verse_paragraph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harmonization',
            options={'ordering': ['verse', 'spot_in_verse']},
        ),
        migrations.AlterModelOptions(
            name='paragraph',
            options={'ordering': ['song', 'order']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['paragraph', 'order']},
        ),
    ]
