# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0005_auto_20170824_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['lastname', 'firstname']},
        ),
        migrations.AlterModelOptions(
            name='chord',
            options={'ordering': ['note']},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['name']},
        ),
    ]
