# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0006_auto_20170902_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='songwriter.Author'),
        ),
        migrations.AlterField(
            model_name='song',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='song',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='songwriter.Editor'),
        ),
    ]
