# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-10 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0007_auto_20170906_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='old_page_number',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='page_number',
            field=models.CharField(blank=True, default='0', max_length=20),
        ),
    ]
