# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-21 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0009_auto_20170919_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlatexcode',
            name='is_compiled',
            field=models.BooleanField(default=False, verbose_name='Is compiled?'),
        ),
    ]
