# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0010_songlatexcode_is_compiled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalLaTeXContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('code', models.TextField(blank=True, verbose_name='Latex code')),
            ],
        ),
    ]
