# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0011_additionallatexcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
