# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-18 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0012_song_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='date added to the database')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date updated to the database')),
                ('song', models.ManyToManyField(related_name='groups', to='songwriter.Song')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
