# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-18 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0013_songsgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songsgroup',
            old_name='song',
            new_name='songs',
        ),
    ]
