# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-23 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0014_auto_20171118_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_refrain',
            field=models.BooleanField(default=False, verbose_name='Is a refrain song?'),
        ),
    ]
