# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0015_song_is_refrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='order_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songsgroup',
            name='order_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songsgroup',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
