# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0017_auto_20171207_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlatexcode',
            name='nb_lines',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
