# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0018_songlatexcode_nb_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsgroup',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='songwriter.Theme'),
        ),
        migrations.AlterField(
            model_name='song',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='songsgroup',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
