# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0019_auto_20171207_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songwriter.Author'),
        ),
        migrations.AlterField(
            model_name='song',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songwriter.Editor'),
        ),
        migrations.AlterField(
            model_name='songsgroup',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='songwriter.Theme'),
        ),
    ]
