# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songwriter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongLaTeXCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, verbose_name='Latex code of a song')),
            ],
        ),
        migrations.AddField(
            model_name='verse',
            name='harmonizations',
            field=models.ManyToManyField(through='songwriter.Harmonization', to='songwriter.Chord'),
        ),
        migrations.AlterField(
            model_name='harmonization',
            name='chord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songwriter.Chord'),
        ),
        migrations.AlterField(
            model_name='harmonization',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songwriter.Verse'),
        ),
        migrations.RemoveField(
            model_name='song',
            name='theme',
        ),
        migrations.AddField(
            model_name='song',
            name='theme',
            field=models.ManyToManyField(to='songwriter.Theme'),
        ),
        migrations.AddField(
            model_name='songlatexcode',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latex_code', to='songwriter.Song'),
        ),
    ]
